default:
  name: Kpw

  static:
    dirs:
      - images
      - css
      - js
      - resources
    include_path:
      - __path_to(./html)__
    ignore_dirs:
      - __path_to(./template)__
    ignore_extensions:
      - tmpl
      - tt
      - tt2

  mail:
    from: korean.perl.workshop@gmail.com

  url: /

  status:
    wait:
      name: 메일 미확인
      message: 사전등록 절차가 제대로 끝나지 않았습니다. 메일을 확인해주세요.
    reserv:
      name: 등록비 미확인
      message: 등록비 확인이 되지 않았습니다. 등록비를 입금하지 않으셨을 경우 아래의 금액을 계좌로 입금해주세요.
    complete:
      name: 사전 등록 완료
      message: Korean Perl Workshop 2008 에 등록해주셔서 감사합니다. 행사 당일 뵙겠습니다.

  messages:
    email:
      NOT_BLANK: eMail 을 입력해주세요
      EMAIL: eMail 양식에 맞게 입력해주세요
    password:
      NOT_BLANK: 비밀번호 를 입력해주세요
    password_confirm:
      NOT_BLANK: 비밀번호_확인 을 입력해주세요
    name:
      NOT_BLANK: 이름 을 입력해주세요
    nick:
      NOT_BLANK: 닉네임 을 입력해주세요
    phone:
      NOT_BLANK: 휴대폰 을 입력해주세요
    tshirt:
      NOT_BLANK: 티셔츠사이즈 를 입력해주세요
    diff_password:
      DIFF: 비밀번호 와 비밀번호_확인 이 맞지않습니다
    user_exist:
      USER_EXIST: 이 eMail 은 이미 등록되어 있습니다
    not_exist;
      NOT_EXIST: 입력하신 eMail 과 패스워드를 다시 한번 확인해주세요
  V:
    DEFAULT: TT
---
