
=encoding euc-jp

=for comment
This document is in Pod format.  To read this, use a Pod formatter,
like "perldoc perlpod".

=head1 NAME

perlpod - the Plain Old Documentation format

=head1 DESCRIPTION

=begin original

Pod is a simple-to-use markup language used for writing documentation
for Perl, Perl programs, and Perl modules.

=end original

Pod 는  Perl, Perl 프로그램, Perl 모듈을 위한 도큐멘트를 쓰기위해
간단히 쓸 수 있는 마크업 언어입니다.

=begin original

Translators are available for converting Pod to various formats
like plain text, HTML, man pages, and more.

=end original

Pod 에서 평문(plain text), HTML, man 페이지 등 여러가지 포맷으로
바꾸기 위한 변환기가 있습니다.

=begin original

Pod markup consists of three basic kinds of paragraphs:
L<ordinary|/"Ordinary Paragraph">,
L<verbatim|/"Verbatim Paragraph">, and 
L<command|/"Command Paragraph">.

=end original

Pod 마크업은 3종류의 단락으로 구성됩니다. 
L<ordinary|/"Ordinary Paragraph">,
L<verbatim|/"Verbatim Paragraph">,
L<command|/"Command Paragraph"> 입니다.


=head2 Ordinary Paragraph

(보통의 단락)

=begin original

Most paragraphs in your documentation will be ordinary blocks
of text, like this one.  You can simply type in your text without
any markup whatsoever, and with just a blank line before and
after.  When it gets formatted, it will undergo minimal formatting, 
like being rewrapped, probably put into a proportionally spaced
font, and maybe even justified.

=end original

아마 대부분의 문서의 단락은 일반적으로 텍스트의 블록입니다.
단순히 어떤 마크업도 사용하지 않고 텍스트를 쓰고, 앞뒤의 빈 줄을 놔둡니다.
포맷팅될때, 최소한의 포맷팅이 수행됩니다.
재래핑이나, 어울리는 폰트에서의 표시나 균등분할 같은 것 말이죠.

=begin original

You can use formatting codes in ordinary paragraphs, for B<bold>,
I<italic>, C<code-style>, L<hyperlinks|perlfaq>, and more.  Such
codes are explained in the "L<Formatting Codes|/"Formatting Codes">"
section, below.

=end original

일반적인 단락에 B<강조> I<이탤릭> C<코드스타일> L<하이퍼링크|perlfaq>
등의 포맷팅코드를 사용할 수도 있습니다.
이런 코드는 아래의 "L<Formatting Codes|/"Formatting Codes">" 의
항목에서 설명하겠습니다.

=head2 Verbatim Paragraph

(말그대로의 단락)

=begin original

Verbatim paragraphs are usually used for presenting a codeblock or
other text which does not require any special parsing or formatting,
and which shouldn't be wrapped.

=end original

그대로의 단락은 코드블록이나 특별한 패스나 포맷팅이 필요없고,
래핑하지 않아도 되는 텍스트를 표현하기 위해 사용됩니다.

=begin original

A verbatim paragraph is distinguished by having its first character
be a space or a tab.  (And commonly, all its lines begin with spaces
and/or tabs.)  It should be reproduced exactly, with tabs assumed to
be on 8-column boundaries.  There are no special formatting codes,
so you can't italicize or anything like that.  A \ means \, and
nothing else.

=end original

공백 혹은 탭에서 시작하는 것으로 인식됩니다.
(간단히 말하면, 이 모든 줄은 공백 혹은 탭으로 시작됩니다)
탭은 8칼럼간격으로 가정되어 그대로 출력됩니다.
특별한 포맷코드는 없으므로, 이탤릭으로 한다거나 하는 것은 없습니다.
\ 은 \으로, 그 외의 의미는 없습니다.

=head2 Command Paragraph

(커맨드 단락)

=begin original

A command paragraph is used for special treatment of whole chunks
of text, usually as headings or parts of lists.

=end original

커맨드 단락은 텍스트의 덩어리 전체를 특별한 취급을 하기 위해 사용됩니다.
보통은 표제나 리스트로써 이용됩니다.

=begin original

All command paragraphs (which are typically only one line long) start
with "=", followed by an identifier, followed by arbitrary text that
the command can use however it pleases.  Currently recognized commands
are

=end original

모든 커맨드단락(전형적으로는 첫줄부터)은 "="로 시작되며,
그 뒤는 식별자가 붙고,  거기에 커맨드를 필요로하는 텍스트가 붙습니다.
현재 사용할수 있는 커맨드는 아래와 같습니다.

    =head1 Heading Text
    =head2 Heading Text
    =head3 Heading Text
    =head4 Heading Text
    =over indentlevel
    =item stuff
    =back
    =cut
    =pod
    =begin format
    =end format
    =for format text...

=begin original

To explain them each in detail:

=end original

아래는 자세한 내용을 설명하고 있습니다.

=over

=item C<=head1 I<Heading Text>>

=item C<=head2 I<Heading Text>>

=item C<=head3 I<Heading Text>>

=item C<=head4 I<Heading Text>>

=begin original

Head1 through head4 produce headings, head1 being the highest
level.  The text in the rest of this paragraph is the content of the
heading.  For example:

=end original

head1 에서 head4 는 표제를 생성합니다. head1 이 최상위입니다.
이 단락의 남은 텍스트는 표제의 내용입니다. 예제:

  =head2 Object Attributes

=begin original

The text "Object Attributes" comprises the heading there.  (Note that
head3 and head4 are recent additions, not supported in older Pod
translators.)  The text in these heading commands can use
formatting codes, as seen here:

=end original

"Object Attributes"라고 하는 텍스트가 여기에서의 표제가 됩니다.
head4는 최근 추가되어서, 옛 Pod 번역기는 안됩니다.
이런 표제 커맨드의 텍스트에서는 아래와 같은 포맷팅코드를 쓸 수 있습니다.

  =head2 Possible Values for C<$/>

=begin original

Such commands are explained in the
"L<Formatting Codes|/"Formatting Codes">" section, below.

=end original

이런 커맨드는 아래의 "L<Formatting Codes|/"Formatting Codes">" 의
항목에서 설명하고 있습니다.

=item C<=over I<indentlevel>>

=item C<=item I<stuff...>>

=item C<=back>

=begin original

Item, over, and back require a little more explanation:  "=over" starts
a region specifically for the generation of a list using "=item"
commands, or for indenting (groups of) normal paragraphs.  At the end
of your list, use "=back" to end it.  The I<indentlevel> option to
"=over" indicates how far over to indent, generally in ems (where
one em is the width of an "M" in the document's base font) or roughly
comparable units; if there is no I<indentlevel> option, it defaults
to four.  (And some formatters may just ignore whatever I<indentlevel>
you provide.)  In the I<stuff> in C<=item I<stuff...>>, you may
use formatting codes, as seen here:

=end original

item, over, back 은 조금 더 설명이 필요합니다:
"=over" 는 "=item" 을 사용한 리스트 생성이나 보통 단락을 인덴트하기 위한
범위지정를 시작합니다.
리스트의 끝에서는 그것을 나타내기 위해 "=back" 를 사용합니다.
"=over"의 I<인덴트레벨> 옵션은 어느 정도 인덴트 할 것인가를 나타내고,
일반적으로 단위는 ems (1 em은 도큐멘트의 기본폰트에서의 "M"의 폭입니다)
나, 혹은 대개 같은 정도의 단위입니다; I<인덴트레벨> 옵션이
없는 경우, 기본값은 4입니다.
(무엇을 I<인덴트레벨> 에 지덩해도 무시하는 서식기도 있습니다)
C<=item I<stuff...>> 의 I<stuff>  안에서는,
아래와 같이 포맷팅코드를 사용할 수 있습니다.

  =item Using C<$|> to Control Buffering

=begin original

Such commands are explained in the
"L<Formatting Codes|/"Formatting Codes">" section, below.

=end original

이런 커맨드는 아래의 "L<Formatting Codes|/"Formatting Codes">" 에서
설명하고 있습니다.

=begin original

Note also that there are some basic rules to using "=over" ...
"=back" regions:

=end original

"=over" ... "=back" 영역을 사용하기 위한 몇가지의 
기본적인 룰이 있는 것에 주의해 주세요.

=over

=item *

=begin original

Don't use "=item"s outside of an "=over" ... "=back" region.

=end original

"=over" ... "=back" 영역 밖에서는 "=item" 은 사용할 수 없습니다.

=item *

=begin original

The first thing after the "=over" command should be an "=item", unless
there aren't going to be any items at all in this "=over" ... "=back"
region.

=end original

"=over" ... "=back" 영역 안에 "=item" 이 전혀 나타나지 않은 것이 아닌 한,
"=over" 커맨드의 뒤, 맨처음에 써진 것은 "=item"이어야 합니다.

=item *

=begin original

Don't put "=headI<n>" commands inside an "=over" ... "=back" region.

=end original

"=over" ... "=back"　영역 안에서 "=headI<n>" 은 사용할 수 없습니다.

=item *

=begin original

And perhaps most importantly, keep the items consistent: either use
"=item *" for all of them, to produce bullets; or use "=item 1.",
"=item 2.", etc., to produce numbered lists; or use "=item foo",
"=item bar", etc. -- namely, things that look nothing like bullets or
numbers.

=end original

그리고, 아마도 제일 중요한 것으로써, item 의 일관성을 유지해 주세요:
점을 출력하기위해서는 모든 item 에 "=item *"를 사용해 주세요;
번호붙은 리스트를 출력하기 위해서는 "=item 1.", "=item 2." 등을 사용해주세요.
점도 번호도 붙지 않는 경우는 "=item foo", "=item bar" 등을 사용해주세요.

=begin original

If you start with bullets or numbers, stick with them, as
formatters use the first "=item" type to decide how to format the
list.

=end original

점 혹은 번호로 시작했다면, 계속 그것을 사용해 주세요.
서식기는 맨 처음의 "=item" 의 타입을 보고 리스트의 포맷방법을 결정합니다.

=back

=item C<=cut>

=begin original

To end a Pod block, use a blank line,
then a line beginning with "=cut", and a blank
line after it.  This lets Perl (and the Pod formatter) know that
this is where Perl code is resuming.  (The blank line before the "=cut"
is not technically necessary, but many older Pod processors require it.)

=end original

Pod 블록을 종료하기 위해서는, 빈 줄, "=cut"로 시작하는 줄, 빈줄을 씁니다.
이것에 의해 Perl (과 Pod 서식기) 는 여기에서 Perl 코드가 다시 시작하는 것을
알게됩니다.
("=cut" 의 앞의 빈 줄은 기술적으로는 필요없지만, 많은 낡은 Pod 프로세서는
이것이 필요합니다)

=item C<=pod>

=begin original

The "=pod" command by itself doesn't do much of anything, but it
signals to Perl (and Pod formatters) that a Pod block starts here.  A
Pod block starts with I<any> command paragraph, so a "=pod" command is
usually used just when you want to start a Pod block with an ordinary
paragraph or a verbatim paragraph.  For example:

=end original

"=pod" 커맨드는 스스로는 거의 아무것도 하지 않지만,
Perl (과 Pod 서식기)에 Pod 블록이 여기에서 시작한다는 것을 나타냅니다.
Pod 블록은 I<어떤> 커맨트 단락에서 시작하므로, 
"=pod" 커맨드는 보ㅇ Pod 블록을 보통의 단락 혹은 그대로의 단락에서
시작하고 싶을 때에 사용합니다. 예제:

  =item stuff()

  This function does stuff.

  =cut

  sub stuff {
    ...
  }

  =pod

  Remember to check its return value, as in:

    stuff() || die "Couldn't do stuff!";

  =cut

=item C<=begin I<formatname>>

=item C<=end I<formatname>>

=item C<=for I<formatname> I<text...>>

=begin original

For, begin, and end will let you have regions of text/code/data that
are not generally interpreted as normal Pod text, but are passed
directly to particular formatters, or are otherwise special.  A
formatter that can use that format will use the region, otherwise it
will be completely ignored.

=end original

for, begin, end 는 일반적인 Pod 텍스트로써 해석되는 것이 아니라,
직접 특정의 서식기에 전달해야하는 텍스트/코드/데이터, 혹은
그 외의 특별한 것의 영역을 정의할 수 있습니다.
이 포맷을 사용하는 포맷은 이 영역을 사용해, 없다면 완전히 무시합니다.

=begin original

A command "=begin I<formatname>", some paragraphs, and a
command "=end I<formatname>", mean that the text/data inbetween
is meant for formatters that understand the special format
called I<formatname>.  For example,

=end original

"=begin I<formatname>" 커맨드, 몇 개정도의 단락 
"=end I<formatname>" 커맨드는 포함된 텍스트/데이터가 
I<formatname> 이라고 불리는 특별한 포맷을 이해하는 서식기용인 것을 의미합니다.
예제:

  =begin html

  <hr> <img src="thang.png">
  <p> This is a raw HTML paragraph </p>

  =end html

=begin original

The command "=for I<formatname> I<text...>"
specifies that the remainder of just this paragraph (starting
right after I<formatname>) is in that special format.  

=end original

"=for I<formatname> I<text...>" 커맨드는 
이 단락의 남은 부분(I<formatname> 의 바로 다음부터)이 특별한 포맷인 것을
정의합니다.

  =for html <hr> <img src="thang.png">
  <p> This is a raw HTML paragraph </p>

=begin original

This means the same thing as the above "=begin html" ... "=end html"
region.

=end original

이것은 위의 "=begin html" ... "=end html" 영역과 같은 의미입니다. 

=begin original

That is, with "=for", you can have only one paragraph's worth
of text (i.e., the text in "=foo targetname text..."), but with
"=begin targetname" ... "=end targetname", you can have any amount
of stuff inbetween.  (Note that there still must be a blank line
after the "=begin" command and a blank line before the "=end"
command.

=end original

이것은, "=for" 에서는 한 단락의 텍스트만을 정의할 수 있습니다만,
(즉 "=foo targetname text...")
"=begin targetname" ... "=end targetname" 에서는 그 사이의 적당량을 
정의합니다.
("=begin" 커맨드의 바로 다음과 "=end" 커맨드의 바로 앞에 빈 줄이 필요하다는
것에 주의해주세요)

=begin original

Here are some examples of how to use these:

=end original

이것을 사용한 예제를 몇 개 정도 들어보도록 합시다.

  =begin html

  <br>Figure 1.<br><IMG SRC="figure1.png"><br>

  =end html

  =begin text

    ---------------
    |  foo        |
    |        bar  |
    ---------------

  ^^^^ Figure 1. ^^^^

  =end text

=begin original

Some format names that formatters currently are known to accept
include "roff", "man", "latex", "tex", "text", and "html".  (Some
formatters will treat some of these as synonyms.)

=end original

현재 사용하는 것의 가능한 포맷이름은 "roff", "man", "latex", "tex",
"text", "html"입니다(일부의 서식기는 다른 것의 별명으로 취급합니다)

=begin original

A format name of "comment" is common for just making notes (presumably
to yourself) that won't appear in any formatted version of the Pod
document:

=end original

포맷이름 "comment"는(아마 작성자를 위한) 간단한 메모로,
포맷팅한 Pod 문서에는 나타나지않아야 할 경우에 사용되는
일반적인 명칭입니다.

  =for comment
  Make sure that all the available options are documented!

=begin original

Some I<formatnames> will require a leading colon (as in
C<"=for :formatname">, or
C<"=begin :formatname" ... "=end :formatname">),
to signal that the text is not raw data, but instead I<is> Pod text
(i.e., possibly containing formatting codes) that's just not for
normal formatting (e.g., may not be a normal-use paragraph, but might
be for formatting as a footnote).

=end original

서식기 중에는 텍스트가 수정되지 않은 데이터가 아닐지라도, Pod 텍스트인
것(즉 포맷팅 코드를 포함하는 것이 있는)을 알리기 위해
C<"=for :formatname"> 나 C<"=begin :formatname" ... "=end :formatname">) 처럼
I<formatnames> 의 앞에 콜론이 필요한 경우도 있습니다. 
(일반적인 단락이 아닌, 각주로써 포맷되는 것 따위입니다) 

=item C<=encoding I<encodingname>>

=begin original

This command is used for declaring the encoding of a document.  Most
users won't need this; but if your encoding isn't US-ASCII or Latin-1,
then put a C<=encoding I<encodingname>> command early in the document so
that pod formatters will know how to decode the document.  For
I<encodingname>, use a name recognized by the L<Encode::Supported>
module.  Examples:

=end original

이 커맨드는 문서의 인코딩을 결정하는 것에 사용됩니다.
대부분의 유저에게는 불필요한 것입니다; 거기다가 만약 인코딩이 
US-ASCII 나 Latin-1 이 아닌 경우,
C<=encoding I<encodingname>> 커맨드를 문서의 시작부분에 놓는 것으로
Pod 서식기가 문서를 어떻게 디코드하면 좋을 지를 알 수 있습니다.
I<encodingname> 에 관해서는 L<Encode::Supported> 에서 인식되는 
이름을 사용해 주세요. 예제:

  =encoding utf8

  =encoding koi8-r
  
  =encoding ShiftJIS
  
  =encoding big5

=back

=begin original

And don't forget, when using any command, that the command lasts up
until the end of its I<paragraph>, not its line.  So in the
examples below, you can see that every command needs the blank
line after it, to end its paragraph.

=end original

そして忘れないで欲しいことは、これらのコマンドを使った場合、その
コマンドが影響するのはコマンドが置かれた行ではなく、
コマンドがあるI<段落>の終端までだということです。ですから先の例には、
各コマンドの後ろに段落を終了させるために空行があるのです。

=begin original

Some examples of lists include:

=end original

幾つか例を挙げましょう:

  =over

  =item *

  First item

  =item *

  Second item

  =back

  =over

  =item Foo()

  Description of Foo function

  =item Bar()

  Description of Bar function

  =back


=head2 Formatting Codes

(フォーマッティングコード)

=begin original

In ordinary paragraphs and in some command paragraphs, various
formatting codes (a.k.a. "interior sequences") can be used:

=end original

普通の段落と、いくつかのコマンド段落では、さまざまな
フォーマッティングコード(またの名を"内部シーケンス")を使うことができます:

=for comment
 "interior sequences" is such an opaque term.
 Prefer "formatting codes" instead.

=over

=item C<IE<lt>textE<gt>> -- italic text

=begin original

Used for emphasis ("C<be IE<lt>careful!E<gt>>") and parameters
("C<redo IE<lt>LABELE<gt>>")

=end original

強調 ("C<be IE<lt>careful!E<gt>>") とパラメータ
("C<redo IE<lt>LABELE<gt>>") のために使います。

=item C<BE<lt>textE<gt>> -- bold text

=begin original

Used for switches ("C<perl's BE<lt>-nE<gt> switch>"), programs
("C<some systems provide a BE<lt>chfnE<gt> for that>"),
emphasis ("C<be BE<lt>careful!E<gt>>"), and so on
("C<and that feature is known as BE<lt>autovivificationE<gt>>").

=end original

スイッチ("C<perl's BE<lt>-nE<gt> switch>"),
プログラム("C<some systems provide a BE<lt>chfnE<gt> for that>"),
強調 ("C<be BE<lt>careful!E<gt>>"), その他
("C<and that feature is known as BE<lt>autovivificationE<gt>>")の
ために使います。

=item C<CE<lt>codeE<gt>> -- code text

=begin original

Renders code in a typewriter font, or gives some other indication that
this represents program text ("C<CE<lt>gmtime($^T)E<gt>>") or some other
form of computerese ("C<CE<lt>drwxr-xr-xE<gt>>").

=end original

コードをタイプライタフォントや、
あるいはプログラムテキスト("C<CE<lt>gmtime($^T)E<gt>>")や
その他のコンピュータ用語("C<CE<lt>drwxr-xr-xE<gt>>") を
表現していることを示すその他の形でレンダリングされます。

=item C<LE<lt>nameE<gt>> -- a hyperlink

=begin original

There are various syntaxes, listed below.  In the syntaxes given,
C<text>, C<name>, and C<section> cannot contain the characters
'/' and '|'; and any '<' or '>' should be matched.

=end original

以下のようにさまざまな文法があります。
文法の中で、C<text>, C<name>, C<section> に '/' と '|' を含むことはできません。
また、'<' や '>' は対応しなければなりません。

=over

=item *

=begin original

C<LE<lt>nameE<gt>>

=end original

C<LE<lt>nameE<gt>>

=begin original

Link to a Perl manual page (e.g., C<LE<lt>Net::PingE<gt>>).  Note
that C<name> should not contain spaces.  This syntax
is also occasionally used for references to UNIX man pages, as in
C<LE<lt>crontab(5)E<gt>>.

=end original

Perl マニュアルページへのリンクを設定します(e.g., C<LE<lt>Net::PingE<gt>>)。
C<name> に空白を含むことができないことに注意してください。
この文法は C<LE<lt>crontab(5)E<gt>> の形で UNIX man ページへの
リファレンスのために使われることもあります。

=item *

=begin original

C<LE<lt>name/"sec"E<gt>> or C<LE<lt>name/secE<gt>>

=end original

C<LE<lt>name/"sec"E<gt>> または C<LE<lt>name/secE<gt>>

=begin original

Link to a section in other manual page.  E.g.,
C<LE<lt>perlsyn/"For Loops"E<gt>>

=end original

他のマニュアルページへのある項目へのリンクを設定します。
例: C<LE<lt>perlsyn/"For Loops"E<gt>>

=item *

=begin original

C<LE<lt>/"sec"E<gt>> or C<LE<lt>/secE<gt>> or C<LE<lt>"sec"E<gt>>

=end original

C<LE<lt>/"sec"E<gt>> または C<LE<lt>/secE<gt>> または C<LE<lt>"sec"E<gt>>

=begin original

Link to a section in this manual page.  E.g.,
C<LE<lt>/"Object Methods"E<gt>>

=end original

このマニュアルページへのある項目へのリンクを設定します。
例: C<LE<lt>/"Object Methods"E<gt>>

=back

=begin original

A section is started by the named heading or item.  For
example, C<LE<lt>perlvar/$.E<gt>> or C<LE<lt>perlvar/"$."E<gt>> both
link to the section started by "C<=item $.>" in perlvar.  And
C<LE<lt>perlsyn/For LoopsE<gt>> or C<LE<lt>perlsyn/"For Loops"E<gt>>
both link to the section started by "C<=head2 For Loops>"
in perlsyn.

=end original

セクションは名前付きの見出しか item で始まります。
たとえば、C<LE<lt>perlvar/$.E<gt>> と C<LE<lt>perlvar/"$."E<gt>> は
両方とも perlvar の "C<=item $.>" で始まるセクションへリンクします。
C<LE<lt>perlsyn/For LoopsE<gt>> と C<LE<lt>perlsyn/"For Loops"E<gt>> は
両方とも perlsyn の "C<=head2 For Loops>" で始まるセクションにリンクします。

=begin original

To control what text is used for display, you
use "C<LE<lt>text|...E<gt>>", as in:

=end original

どんなテキストが表示に用いられるかを制御するためには、
"C<LE<lt>text|...E<gt>>" を使ってください。つまり:

=over

=item *

=begin original

C<LE<lt>text|nameE<gt>>

=end original

C<LE<lt>text|nameE<gt>>

=begin original

Link this text to that manual page.  E.g.,
C<LE<lt>Perl Error Messages|perldiagE<gt>>

=end original

このテキストに指定したマニュアルページへのリンクを設定します。
例: C<LE<lt>Perl Error Messages|perldiagE<gt>>

=item *

=begin original

C<LE<lt>text|name/"sec"E<gt>> or C<LE<lt>text|name/secE<gt>>

=end original

C<LE<lt>text|name/"sec"E<gt>> または C<LE<lt>text|name/secE<gt>>

=begin original

Link this text to that section in that manual page.  E.g.,
C<LE<lt>SWITCH statements|perlsyn/"Basic BLOCKs and Switch
Statements"E<gt>>

=end original

このテキストに指定したマニュアルページのある項目へのリンクを設定します。
例: C<LE<lt>SWITCH statements|perlsyn/"Basic BLOCKs and Switch
Statements"E<gt>>

=item *

=begin original

C<LE<lt>text|/"sec"E<gt>> or C<LE<lt>text|/secE<gt>>
or C<LE<lt>text|"sec"E<gt>>

=end original

C<LE<lt>text|/"sec"E<gt>> または C<LE<lt>text|/secE<gt>>
または C<LE<lt>text|"sec"E<gt>>

=begin original

Link this text to that section in this manual page.  E.g.,
C<LE<lt>the various attributes|/"Member Data"E<gt>>

=end original

このテキストにこのマニュアルページのある項目へのリンクを設定します。
例: C<LE<lt>the various attributes|/"Member Data"E<gt>>

=back

=begin original

Or you can link to a web page:

=end original

web ページにリンクを設定することもできます。

=over

=item *

=begin original

C<LE<lt>scheme:...E<gt>>

=end original

C<LE<lt>scheme:...E<gt>>

=begin original

Links to an absolute URL.  For example,
C<LE<lt>http://www.perl.org/E<gt>>.  But note
that there is no corresponding C<LE<lt>text|scheme:...E<gt>> syntax, for
various reasons.

=end original

絶対 URL へのリンクです。例: C<LE<lt>http://www.perl.org/E<gt>>。
しかし、さまざまな理由により、対応する C<LE<lt>text|scheme:...E<gt>> という
文法はないことに注意してください。

=back

=item C<EE<lt>escapeE<gt>> -- a character escape

=begin original

Very similar to HTML/XML C<&I<foo>;> "entity references":

=end original

HTML/XML C<&I<foo>;> "実体参照"ととても似ています。

=over

=item *

=begin original

C<EE<lt>ltE<gt>> -- a literal E<lt> (less than)

=end original

C<EE<lt>ltE<gt>> -- リテラルの E<lt> (less than)

=item *

=begin original

C<EE<lt>gtE<gt>> -- a literal E<gt> (greater than)

=end original

C<EE<lt>gtE<gt>> -- リテラルの E<gt> (greater than)

=item *

=begin original

C<EE<lt>verbarE<gt>> -- a literal | (I<ver>tical I<bar>)

=end original

C<EE<lt>verbarE<gt>> -- リテラルの | (I<ver>tical I<bar>)

=item *

=begin original

C<EE<lt>solE<gt>> = a literal / (I<sol>idus)

=end original

C<EE<lt>solE<gt>> = リテラルの / (I<sol>idus)

=begin original

The above four are optional except in other formatting codes,
notably C<LE<lt>...E<gt>>, and when preceded by a
capital letter.

=end original

上記の 4 つは他のフォーマッティングコードの中
(特に C<LE<lt>...E<gt>>)と、大文字が前につけられた場合を除いて
オプションです。

=item *

=begin original

C<EE<lt>htmlnameE<gt>>

=end original

C<EE<lt>htmlnameE<gt>>

=begin original

Some non-numeric HTML entity name, such as C<EE<lt>eacuteE<gt>>,
meaning the same thing as C<&eacute;> in HTML -- i.e., a lowercase
e with an acute (/-shaped) accent.

=end original

いくつかの数値でない HTML エンティティ名(C<EE<lt>eacuteE<gt>> のようなもの)は
HTML での C<&eacute;> と同じ意味です -- つまり、
acute (/-の形の) アクサン付きの小文字の e です。

=item *

=begin original

C<EE<lt>numberE<gt>>

=end original

C<EE<lt>numberE<gt>>

=begin original

The ASCII/Latin-1/Unicode character with that number.  A
leading "0x" means that I<number> is hex, as in
C<EE<lt>0x201EE<gt>>.  A leading "0" means that I<number> is octal,
as in C<EE<lt>075E<gt>>.  Otherwise I<number> is interpreted as being
in decimal, as in C<EE<lt>181E<gt>>.

=end original

この番号の ASCII/Latin-1/Unicode 文字です。
C<EE<lt>0x201EE<gt>> のように先頭に "0x" があると I<number> は 16 進数です。
C<EE<lt>075E<gt>> のように先頭に "0" があると I<number> は 8 進数です。
C<EE<lt>181E<gt>> のようにそれ以外では I<number> は 10 進数と解釈されます。

=begin original

Note that older Pod formatters might not recognize octal or
hex numeric escapes, and that many formatters cannot reliably
render characters above 255.  (Some formatters may even have
to use compromised renderings of Latin-1 characters, like
rendering C<EE<lt>eacuteE<gt>> as just a plain "e".)

=end original

古い Pod フォーマッタは 8 進数や 16 進数のエスケープを認識しない
可能性があり、また多くのフォーマッタは 255 以上の文字を
正しくレンダリングできるかわからないことに注意してください。
(Latin-1 文字ですら正しくレンダリングできないフォーマッタもあります。
例えば C<EE<lt>eacuteE<gt>> を普通の "e" にレンダリングします。)

=back

=item C<FE<lt>filenameE<gt>> -- used for filenames

=begin original

Typically displayed in italics.  Example: "C<FE<lt>.cshrcE<gt>>"

=end original

典型的にはイタリックで表示されます。例: "C<FE<lt>.cshrcE<gt>>"

=item C<SE<lt>textE<gt>> -- text contains non-breaking spaces

=begin original

This means that the words in I<text> should not be broken
across lines.  Example: S<C<SE<lt>$x ? $y : $zE<gt>>>.

=end original

これは I<text> の内容が行をまたがないことを意味します。
例: <C<SE<lt>$x ? $y : $zE<gt>>>

=item C<XE<lt>topic nameE<gt>> -- an index entry

=begin original

This is ignored by most formatters, but some may use it for building
indexes.  It always renders as empty-string.
Example: C<XE<lt>absolutizing relative URLsE<gt>>

=end original

これは多くのフォーマッタでは無視されますが、
インデックスを作成するのに使われることもあります。
常に空文字列としてレンダリングされます。
例: C<XE<lt>absolutizing relative URLsE<gt>>

=item C<ZE<lt>E<gt>> -- a null (zero-effect) formatting code

=begin original

This is rarely used.  It's one way to get around using an
EE<lt>...E<gt> code sometimes.  For example, instead of
"C<NEE<lt>ltE<gt>3>" (for "NE<lt>3") you could write
"C<NZE<lt>E<gt>E<lt>3>" (the "ZE<lt>E<gt>" breaks up the "N" and
the "E<lt>" so they can't be considered
the part of a (fictitious) "NE<lt>...E<gt>" code.

=end original

これはまれに用いられます。
ときどき EE<lt>...E<gt> コードを使う方法の一つです。
例えば、("NE<lt>3" のために) "C<NEE<lt>ltE<gt>3>" の代わりに
"C<NZE<lt>E<gt>E<lt>3>" と書けます。
(the "ZE<lt>E<gt>" は "N" と "E<lt>" を分解するので
"NE<lt>...E<gt>" の一部と(間違って)解釈されることはありません。)

=for comment
 This was formerly explained as a "zero-width character".  But it in
 most parser models, it parses to nothing at all, as opposed to parsing
 as if it were a E<zwnj> or E<zwj>, which are REAL zero-width characters.
 So "width" and "character" are exactly the wrong words.

=back

=begin original

Most of the time, you will need only a single set of angle brackets to
delimit the beginning and end of formatting codes.  However,
sometimes you will want to put a real right angle bracket (a
greater-than sign, '>') inside of a formatting code.  This is particularly
common when using a formatting code to provide a different font-type for a
snippet of code.  As with all things in Perl, there is more than
one way to do it.  One way is to simply escape the closing bracket
using an C<E> code:

=end original

たいていの場合、コードフォーマッティングの最初と最後のデリミタとして
1 組の山括弧のみが必要です。
しかし、時々フォーマッティングコードの中に右山括弧(または大なり記号'>')を
入れたい場合があります。これはコードの断片の中で違うフォントタイプを
使いたいときによくあります。
Perl に関する他のことと同様に、やりかたはひとつではありません。
ひとつの方法は単純に閉じ括弧を C<E> コードを使って
エスケープする方法です:

    C<$a E<lt>=E<gt> $b>

=begin original

This will produce: "C<$a E<lt>=E<gt> $b>"

=end original

これは "C<$a E<lt>=E<gt> $b>" となります。

=begin original

A more readable, and perhaps more "plain" way is to use an alternate
set of delimiters that doesn't require a single ">" to be escaped.  With
the Pod formatters that are standard starting with perl5.5.660, doubled
angle brackets ("<<" and ">>") may be used I<if and only if there is
whitespace right after the opening delimiter and whitespace right
before the closing delimiter!>  For example, the following will
do the trick:

=end original

より読みやすく、そしておそらくより"明白な"方法は、別のデリミタを
使って、単独の">"をエスケープしなくてもいいようにする方法です。
Perl5.5.660 以降の Pod フォーマッタでは、2 個の山括弧 ("<<" and ">>")が使えます。
但し、I<開始デリミタの直後と終了デリミタの直前に空白があるときだけ>です!
例えば、以下はそのトリックを使っています:

    C<< $a <=> $b >>

=begin original

In fact, you can use as many repeated angle-brackets as you like so
long as you have the same number of them in the opening and closing
delimiters, and make sure that whitespace immediately follows the last
'<' of the opening delimiter, and immediately precedes the first '>'
of the closing delimiter.  (The whitespace is ignored.)  So the
following will also work:

=end original

実際のところ、開始デリミタと終了デリミタの数さえ合っており、
開始デリミタの最後の '<' の直後と 終了デリミタの最初の '>' の
直前に空白が入っていれば、
山括弧の数はいくつでもかまいません。
(空白は無視されます。)
従って、以下のものも正しく動作します:

    C<<< $a <=> $b >>>
    C<<<<  $a <=> $b     >>>>

=begin original

And they all mean exactly the same as this:

=end original

そしてこれらは全て以下と全く同じ意味です:

    C<$a E<lt>=E<gt> $b>

=begin original

As a further example, this means that if you wanted to put these bits of
code in C<C> (code) style:

=end original

さらなる例として、C<C> (コード) スタイルのコードの断片を書きたいとすると:

    open(X, ">>thing.dat") || die $!
    $foo->bar();

=begin original

you could do it like so:

=end original

以下のように書くことができます:

    C<<< open(X, ">>thing.dat") || die $! >>>
    C<< $foo->bar(); >>

=begin original

which is presumably easier to read than the old way:

=end original

これはおそらく以下のような古い書き方より読みやすいです:

    C<open(X, "E<gt>E<gt>thing.dat") || die $!>
    C<$foo-E<gt>bar();>

=begin original

This is currently supported by pod2text (Pod::Text), pod2man (Pod::Man),
and any other pod2xxx or Pod::Xxxx translators that use
Pod::Parser 1.093 or later, or Pod::Tree 1.02 or later.

=end original

これは現在のところ pod2text (Pod::Text), pod2man (Pod::Man), および
Pod::Parser 1.093 以降、Pod::Tree 1.02 以降を使用しているその他の
pod2xxx と Pod::Xxxx が対応しています。

=head2 The Intent

(目的)

=begin original

The intent is simplicity of use, not power of expression.  Paragraphs
look like paragraphs (block format), so that they stand out
visually, and so that I could run them through C<fmt> easily to reformat
them (that's F7 in my version of B<vi>, or Esc Q in my version of
B<emacs>).  I wanted the translator to always leave the C<'> and C<`> and
C<"> quotes alone, in verbatim mode, so I could slurp in a
working program, shift it over four spaces, and have it print out, er,
verbatim.  And presumably in a monospace font.

=end original

表現力ではなく簡単に使えるものを目指しています。
段落は段落らしく(矩形に)見えて欲しいので、見た目に目立ち、
C<fmt> で簡単に再整形できるようになっています (私の B<vi> では
F7 に、B<emacs> では Esc Q になっています)。
私が求めていたのは、verbatim モードでは C<'> や C<`> や C<"> のクォートを
そのままにしておいて欲しかったのです。そうすれば、作りかけの
プログラムを放り込んで、4 カラムずらして、
それをそのまま印刷すればいいのです。たぶん、固定幅のフォントで。

=begin original

The Pod format is not necessarily sufficient for writing a book.  Pod
is just meant to be an idiot-proof common source for nroff, HTML,
TeX, and other markup languages, as used for online
documentation.  Translators exist for B<pod2text>, B<pod2html>,
B<pod2man> (that's for nroff(1) and troff(1)), B<pod2latex>, and
B<pod2fm>.  Various others are available in CPAN.

=end original

Pod フォーマットは本を作るのに十分である必要はありません。
Pod はただ、オンラインドキュメントに使うnroff やTeXといったマークアップ言語の
ための、誰にでも使える共通のソースを提供しています。
現在あるトランスレータには B<pod2text>, B<pod2html>, 
B<pod2man>  (nroff(1) や troff(1)用), B<pod2latex>, B<pod2fm>があります。
他にもさまざまなものが CPAN にあります。

=head2 Embedding Pods in Perl Modules

(Perlモジュールへのpodの埋め込み)

=begin original

You can embed Pod documentation in your Perl modules and scripts.
Start your documentation with an empty line, a "=head1" command at the
beginning, and end it with a "=cut" command and an empty line.  Perl
will ignore the Pod text.  See any of the supplied library modules for
examples.  If you're going to put your Pod at the end of the file, and
you're using an __END__ or __DATA__ cut mark, make sure to put an
empty line there before the first Pod command.

=end original

Perl モジュールとスクリプトに Pod ドキュメントを埋め込むことができます。
ドキュメントを空行および“=head1”コマンドで始め、“=cut”と空行で終えます。
Perl はこのような Pod テキストを無視します。
実例はあなたの使っているライブラリモジュールにあります。
もし Pod テキストをファイルの末尾に置きたいというのであれば、
__END__ や __DATA__ というカットマークを置き、
さらに最初に現れる Pod コマンドの前に空行を置くことで行うことができます。

  __END__

  =head1 NAME

  Time::Local - efficiently compute time from local and GMT time

=begin original

Without that empty line before the "=head1", many translators wouldn't
have recognized the "=head1" as starting a Pod block.

=end original

"=head1" の前に空行がない場合、多くのトランスレータは"=head1"が
Pod ブロックの開始と認識しません。

=head2 Hints for Writing Pod

(Pod を書くためのヒント)

=over

=item *

=begin original

The B<podchecker> command is provided for checking Pod syntax for errors
and warnings.  For example, it checks for completely blank lines in
Pod blocks and for unknown commands and formatting codes.  You should
still also pass your document through one or more translators and proofread
the result, or print out the result and proofread that.  Some of the
problems found may be bugs in the translators, which you may or may not
wish to work around.

=end original

B<podchecker> コマンドは Pod の文法に関するエラーと警告を
チェックするために提供されています。
例えば、Pod の分割に完全な空行が使われているかや、
不明なコマンドやフォーマットコードなどをチェックします。
それでも一つまたは複数のトランスレータに通して結果をチェックするか、
結果を印刷してそれをチェックすることをお勧めします。
発見した問題の中には、回避しようと思ったり思わなかったりするような
トランスレータのバグもあるでしょう。

=item *

=begin original

If you're more familiar with writing in HTML than with writing in Pod, you
can try your hand at writing documentation in simple HTML, and converting
it to Pod with the experimental L<Pod::HTML2Pod|Pod::HTML2Pod> module,
(available in CPAN), and looking at the resulting code.  The experimental
L<Pod::PXML|Pod::PXML> module in CPAN might also be useful.

=end original

もしあなたが Pod を書くことより HTML を書くことに慣れているなら、
単純な HTML でドキュメントを書き、実験的な L<Pod::HTML2Pod|Pod::HTML2Pod>
モジュール (CPAN にあります)を使って Pod に変換することを試すこともできます。
CPAN にある 実験的な L<Pod::PXML|Pod::PXML> も有用です。

=item *

=begin original

Many older Pod translators require the lines before every Pod
command and after every Pod command (including "=cut"!) to be a blank
line.  Having something like this:

=end original

多くの古い Pod トランスレータは全ての Pod コマンド("=cut" を含みます!)の
前後に空行が必要です。以下のように書くと:

 # - - - - - - - - - - - -
 =item $firecracker->boom()

 This noisily detonates the firecracker object.
 =cut
 sub boom {
 ...

=begin original

...will make such Pod translators completely fail to see the Pod block
at all.

=end original

そのような Pod トランスレータは Pod ブロックの発見に完全に
失敗するでしょう。

=begin original

Instead, have it like this:

=end original

代わりに、以下のように書いてください:

 # - - - - - - - - - - - -

 =item $firecracker->boom()

 This noisily detonates the firecracker object.

 =cut

 sub boom {
 ...

=item *

=begin original

Some older Pod translators require paragraphs (including command
paragraphs like "=head2 Functions") to be separated by I<completely>
empty lines.  If you have an apparently empty line with some spaces
on it, this might not count as a separator for those translators, and
that could cause odd formatting.

=end original

古い Pod トランスレータには、段落("=head2 Functions" のような
コマンド段落も含みます)の分割にI<完全な>空行を必要とするものもあります。
空白の入った見た目空行のようなものを入れると、
セパレータとして扱われずに出力がおかしくなるかもしれません。

=item *

=begin original

Older translators might add wording around an LE<lt>E<gt> link, so that
C<LE<lt>Foo::BarE<gt>> may become "the Foo::Bar manpage", for example.
So you shouldn't write things like C<the LE<lt>fooE<gt>
documentation>, if you want the translated document to read sensibly
-- instead write C<the LE<lt>Foo::Bar|Foo::BarE<gt> documentation> or
C<LE<lt>the Foo::Bar documentation|Foo::BarE<gt>>, to control how the
link comes out.

=end original

古いトランスレータは LE<lt>E<gt> リンクに語の追加を行う場合があります。
このため、たとえば C<LE<lt>Foo::BarE<gt>> は“the Foo::Bar manpage”と
なります(詳しくはB<pod2man>を参照)。
したがって、あなたは変換されたドキュメントを読みやすいものにするために、
C<the LE<lt>fooE<gt> documentation>という書き方はすべきではありません
-- 代わりに C<the LE<lt>Foo::Bar|Foo::BarE<gt> documentation> と
書くか、どのようにリンクが出来るかを制御するために 
C<LE<lt>the Foo::Bar documentation|Foo::BarE<gt>> としてください。

=item *

=begin original

Going past the 70th column in a verbatim block might be ungracefully
wrapped by some formatters.

=end original

そのままのブロックで 70 文字を越えると、フォーマッタによっては
見苦しいラッピングが行われるかもしれません。

=back

=head1 SEE ALSO

L<perlpodspec>, L<perlsyn/"PODs: Embedded Documentation">,
L<perlnewmod>, L<perldoc>, L<pod2html>, L<pod2man>, L<podchecker>.

=head1 AUTHOR

Larry Wall, Sean M. Burke

=begin meta

Translate: 吉村 寿人 <JAE00534@niftyserve.or.jp>
Update: Kentaro Shirakata <argrath@ub32.org>
License: GPL or Artistic

=end meta

=cut

